CREATE TABLE STATS (
                       STAT_ID INT(11) AUTO_INCREMENT PRIMARY KEY,
                       STAT_DATE DATETIME NOT NULL,
                       STAT VARCHAR(20) NOT NULL,
                       VALUE INT(11) NOT NULL
);

CREATE VIEW BESTSELLERS_COUNT AS
SELECT COUNT(*) FROM BOOKS
WHERE BOOKS.BESTSELLER = TRUE;

SELECT * FROM BESTSELLERS_COUNT;


USE KODILLA_COURSE;

CREATE EVENT UPDATE_BESTSELLERS
    ON SCHEDULE EVERY 1 MINUTE
    DO
        BEGIN
            DECLARE counter INT;
            CALL UpdateBestsellers();
            SELECT * FROM BESTSELLERS_COUNT
                INTO counter;
            INSERT INTO STATS(STAT_DATE, STAT, VALUE)
                VALUES (CURDATE(),'BESTSELLERS',counter);
        END;

UPDATE BOOKS
SET BESTSELLER = FALSE;

SELECT * FROM BOOKS;
SELECT * FROM STATS;
SHOW PROCESSLIST;